<?php include 'head.php'; ?>
<h1>stack.</h1>

<h2 id="chat_h">chat...</h2>
<h2 id="blog_h">blog...</h2>
<h2 id="file_h">file...</h2>

<div id="chat">
	<?php include 'chat.php' ?>
	<p>
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat 
	chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat chat
	</p>
</div>

<div id="blog">
	<?php include 'blog.php' ?>
	<br/>
	<p>
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog 
	blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog blog
	</p>
</div>

<div id="file">
	<?php include 'file.php' ?>
	<br/>
	<p>
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file 
	file file file file file file file file file file file file file file file file file file file file
	</p>
</div>

<?php include 'tail.php'; ?>